# For more information, visit https://github.com/realm/SwiftLint

disabled_rules:
  nesting
opt_in_rules:
  - trailing_comma
  - file_header

included:
  - .
excluded:
  - .build
  - Package.swift

file_header:
  required_pattern: |
    \/\/
    \/\/  .*?\.swift
    \/\/  (App|AppTests|Run)
    \/\/
    \/\/  Created by .*? on \d{2}\/\d{2}\/\d{4}\.
    \/\/  Copyright (©|\(c\)) \d{4} Monki Projects\. All rights reserved\.
    \/\/

line_length: 110
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1200
identifier_name:
  excluded:
    - id
    - url
    - lhs
    - rhs
    - en
    - fr
    - v1
    - n
trailing_whitespace:
  ignores_empty_lines: true
trailing_comma:
  mandatory_comma: true
reporter: "xcode"
