name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      # Build everything, with test discovery
      run: swift build --enable-test-discovery
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: swift test --skip-build --parallel
