name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Run tests
      run: swift test --enable-test-discovery --parallel
