name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests with Thread Sanitizer
      run: swift test --enable-test-discovery --sanitize=thread
