name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests in parallel and with Thread Sanitizer
      run: swift test --enable-test-discovery --parallel # --sanitize=thread
